# coding: utf-8

"""
    Web API Swagger specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FileSource(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'file_path': 'str',
        'file_source_type': 'str'
    }

    attribute_map = {
        'file_path': 'FilePath',
        'file_source_type': 'FileSourceType'
    }
    
    @staticmethod
    def get_swagger_types():
        return FileSource.swagger_types
    
    @staticmethod
    def get_attribute_map():
        return FileSource.attribute_map
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, file_path=None, file_source_type=None, **kw):
        """
        Associative dict for storing property values
        """
        self.container = {}
		    
        """
        FileSource - a model defined in Swagger
        """

        self.container['file_path'] = None
        self.container['file_source_type'] = None

        if file_path is not None:
          self.file_path = file_path
        if file_source_type is not None:
          self.file_source_type = file_source_type

    @property
    def file_path(self):
        """
        Gets the file_path of this FileSource.

        :return: The file_path of this FileSource.
        :rtype: str
        """
        return self.container['file_path']

    @file_path.setter
    def file_path(self, file_path):
        """
        Sets the file_path of this FileSource.

        :param file_path: The file_path of this FileSource.
        :type: str
        """

        self.container['file_path'] = file_path

    @property
    def file_source_type(self):
        """
        Gets the file_source_type of this FileSource.

        :return: The file_source_type of this FileSource.
        :rtype: str
        """
        return self.container['file_source_type']

    @file_source_type.setter
    def file_source_type(self, file_source_type):
        """
        Sets the file_source_type of this FileSource.

        :param file_source_type: The file_source_type of this FileSource.
        :type: str
        """

        self.container['file_source_type'] = file_source_type

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FileSource):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
