# coding: utf-8

"""
    Web API Swagger specification

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class WorksheetMovingRequest(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'destination_worksheet': 'str',
        'position': 'str'
    }

    attribute_map = {
        'destination_worksheet': 'DestinationWorksheet',
        'position': 'Position'
    }
    
    def get_swagger_types(self):
        return WorksheetMovingRequest.swagger_types
        
    def get_attribute_map(self):
        return WorksheetMovingRequest.attribute_map
    
    """
        Associative dict for storing property values
    """
    container = {}
    
    def get_from_container(self, attr):
        if attr in self.container:
            return self.container[attr]
        return None

    def __init__(self, destination_worksheet=None, position=None):
        """
        WorksheetMovingRequest - a model defined in Swagger
        """

        self.container['destination_worksheet'] = None
        self.container['position'] = None

        if destination_worksheet is not None:
          self.destination_worksheet = destination_worksheet
        if position is not None:
          self.position = position

    @property
    def destination_worksheet(self):
        """
        Gets the destination_worksheet of this WorksheetMovingRequest.
        Destination worksheet name.  

        :return: The destination_worksheet of this WorksheetMovingRequest.
        :rtype: str
        """
        return self.container['destination_worksheet']

    @destination_worksheet.setter
    def destination_worksheet(self, destination_worksheet):
        """
        Sets the destination_worksheet of this WorksheetMovingRequest.
        Destination worksheet name.  

        :param destination_worksheet: The destination_worksheet of this WorksheetMovingRequest.
        :type: str
        """

        self.container['destination_worksheet'] = destination_worksheet

    @property
    def position(self):
        """
        Gets the position of this WorksheetMovingRequest.
        Position to move. Can be BEFORE or AFTER.

        :return: The position of this WorksheetMovingRequest.
        :rtype: str
        """
        return self.container['position']

    @position.setter
    def position(self, position):
        """
        Sets the position of this WorksheetMovingRequest.
        Position to move. Can be BEFORE or AFTER.

        :param position: The position of this WorksheetMovingRequest.
        :type: str
        """

        self.container['position'] = position

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.get_swagger_types()):
            value = self.get_from_container(attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, WorksheetMovingRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
